Repository EnjoytripDS/Travelary_Backend, pull requests merged in 2023-05, with the labels that each got.

#18 [Feature/08] q&a 게시판
  pom.xml
  src/main/java/com/ssafy/enjoytrip/commons/config/WebConfig.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/controller/QnaBoardController.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dao/QnaBoardDao.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dto/QnaBoard.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dto/QnaBoardView.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dto/request/CreateQnaBoardRequest.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/exception/QnaBoardNotFoundException.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/QnaBoardService.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/QnaBoardServiceImpl.java
  src/main/java/com/ssafy/enjoytrip/user/dto/User.java
  src/main/java/com/ssafy/enjoytrip/user/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mappers/QnaBoardMapper.xml
  src/main/resources/mappers/UserMapper.xml
Labels: ✨Feat, Revise

#25 [Feature/10] 마이페이지 관련 User 수정
  pom.xml
  src/main/java/com/ssafy/enjoytrip/commons/auth/LoginCheckInterceptor.java
  src/main/java/com/ssafy/enjoytrip/commons/config/WebConfig.java
  src/main/java/com/ssafy/enjoytrip/user/controller/UserController.java
  src/main/java/com/ssafy/enjoytrip/user/dto/User.java
  src/main/java/com/ssafy/enjoytrip/user/dto/request/ModifyUserRequest.java
  src/main/java/com/ssafy/enjoytrip/user/dto/response/LoginResponse.java
  src/main/java/com/ssafy/enjoytrip/user/service/UserService.java
  src/main/java/com/ssafy/enjoytrip/user/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mappers/UserMapper.xml
Labels: ✨Feat

#30 [Feature/11] swagger 설정 및 Custom Exception/Response, ExceptionHandling
  mvnw.cmd
  src/main/java/com/ssafy/enjoytrip/commons/exception/BaseException.java
  src/main/java/com/ssafy/enjoytrip/commons/exception/ErrorCode.java
  src/main/java/com/ssafy/enjoytrip/commons/exception/GlobalControllerAdvice.java
  src/main/java/com/ssafy/enjoytrip/commons/response/CommonApiResponse.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/exception/QnaBoardNotFoundException.java
  src/main/java/com/ssafy/enjoytrip/user/controller/UserController.java
  src/main/java/com/ssafy/enjoytrip/user/dto/User.java
  src/main/java/com/ssafy/enjoytrip/user/exception/InvalidPasswordException.java
  src/main/java/com/ssafy/enjoytrip/user/exception/PasswordFailException.java
  src/main/java/com/ssafy/enjoytrip/user/exception/UserDuplicatedEmailException.java
  src/main/java/com/ssafy/enjoytrip/user/exception/UserDuplicatedNicknameException.java
  src/main/java/com/ssafy/enjoytrip/user/exception/UserNotFoundException.java
  src/main/java/com/ssafy/enjoytrip/user/service/UserServiceImpl.java
Labels: ✨Feat, ♻️Refactor

#31 Fix: 로그인 및 회원가입 수정
  pom.xml
  src/main/java/com/ssafy/enjoytrip/commons/auth/JwtInterceptor.java
  src/main/java/com/ssafy/enjoytrip/commons/auth/LoginCheckInterceptor.java
  src/main/java/com/ssafy/enjoytrip/commons/config/WebConfig.java
  src/main/java/com/ssafy/enjoytrip/commons/exception/GlobalControllerAdvice.java
  src/main/java/com/ssafy/enjoytrip/commons/exception/UnAuthorizedException.java
  src/main/java/com/ssafy/enjoytrip/commons/jwt/service/JwtService.java
  src/main/java/com/ssafy/enjoytrip/commons/jwt/service/JwtServiceImpl.java
  src/main/java/com/ssafy/enjoytrip/user/controller/UserController.java
  src/main/java/com/ssafy/enjoytrip/user/dao/UserDao.java
  src/main/java/com/ssafy/enjoytrip/user/dto/User.java
  src/main/java/com/ssafy/enjoytrip/user/dto/request/LoginRequest.java
  src/main/java/com/ssafy/enjoytrip/user/dto/request/ModifyPwdRequest.java
  src/main/java/com/ssafy/enjoytrip/user/dto/response/LoginResponse.java
  src/main/java/com/ssafy/enjoytrip/user/service/UserService.java
  src/main/java/com/ssafy/enjoytrip/user/service/UserServiceImpl.java
  src/main/resources/mappers/UserMapper.xml
Labels: 🐛Bug, ✨Feat

#32 Fix: AttractionController 파라미터 수정
  src/main/java/com/ssafy/enjoytrip/attraction/controller/AttractionController.java
Labels: 🐛Bug

#35 [Feature/09-2] 관광지 상세 조회 및 구/군 리스트 api 충돌 문제 해결 / Swagger api 작성
  src/main/java/com/ssafy/enjoytrip/attraction/controller/AttractionController.java
  src/main/java/com/ssafy/enjoytrip/attraction/dao/AttractionDao.java
  src/main/java/com/ssafy/enjoytrip/attraction/dto/Attraction.java
  src/main/java/com/ssafy/enjoytrip/attraction/service/AttractionService.java
  src/main/java/com/ssafy/enjoytrip/attraction/service/AttractionServiceImpl.java
  src/main/java/com/ssafy/enjoytrip/commons/exception/GlobalControllerAdvice.java
  src/main/java/com/ssafy/enjoytrip/user/dto/request/ModifyUserRequest.java
  src/main/resources/mappers/AttractionMapper.xml
Labels: 🐛Bug, ✨Feat

#36 [Fix/03] session -> jwt로 변경하면서 불필요한 import 제거
  src/main/java/com/ssafy/enjoytrip/user/controller/UserController.java
Labels: 🐛Bug

#37 [Feature/13] 구군 리스트 response 변경
  src/main/java/com/ssafy/enjoytrip/attraction/controller/AttractionController.java
  src/main/java/com/ssafy/enjoytrip/attraction/dao/AttractionDao.java
  src/main/java/com/ssafy/enjoytrip/attraction/dto/Gugun.java
  src/main/java/com/ssafy/enjoytrip/attraction/service/AttractionService.java
  src/main/java/com/ssafy/enjoytrip/attraction/service/AttractionServiceImpl.java
  src/main/resources/mappers/AttractionMapper.xml
Labels: Revise

#39 [Feature/15] 게시판 댓글
  src/main/java/com/ssafy/enjoytrip/qnaboard/controller/QnaBoardController.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dao/QnaBoardDao.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dto/BoardComment.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dto/request/CreateBoardCommentRequest.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/BoardCommentService.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/BoardCommentServiceImpl.java
  src/main/resources/mappers/QnaBoardMapper.xml
Labels: ✨Feat

#42 Feat: 여행 후기 게시판 파일 업로드 구현
  src/main/java/com/ssafy/enjoytrip/commons/config/WebConfig.java
  src/main/java/com/ssafy/enjoytrip/commons/exception/ErrorCode.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/controller/QnaBoardController.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dao/QnaBoardDao.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dto/BoardImage.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/exception/ImageNotFoundException.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/BoardImageService.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/BoardImageServiceImpl.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/QnaBoardService.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/QnaBoardServiceImpl.java
  src/main/resources/mappers/QnaBoardMapper.xml
  src/main/resources/mappers/TripMapper.xml
Labels: ✨Feat

#43 Fix: Trip Mapper (1)
  src/main/java/com/ssafy/enjoytrip/trip/controller/TripController.java
  src/main/java/com/ssafy/enjoytrip/trip/dto/Trip.java
  src/main/java/com/ssafy/enjoytrip/trip/dto/TripAttraction.java
  src/main/java/com/ssafy/enjoytrip/trip/dto/request/CreateTripRequest.java
  src/main/resources/mappers/TripMapper.xml
Labels: 🐛Bug

#45 [Fix/04] 마이 페이지 수정 및 게시판 오류 수정
  src/main/java/com/ssafy/enjoytrip/qnaboard/controller/QnaBoardController.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/dao/QnaBoardDao.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/BoardImageService.java
  src/main/java/com/ssafy/enjoytrip/qnaboard/service/BoardImageServiceImpl.java
  src/main/java/com/ssafy/enjoytrip/user/controller/UserController.java
  src/main/java/com/ssafy/enjoytrip/user/dto/User.java
  src/main/java/com/ssafy/enjoytrip/user/dto/request/ModifyPwdRequest.java
  src/main/java/com/ssafy/enjoytrip/user/service/UserServiceImpl.java
  src/main/resources/mappers/QnaBoardMapper.xml
Labels: 🐛Bug, ✨Feat, Revise
